export const SUCCESS = 200;
export const INTERNAL_SERVER_ERROR = 500;
export const NOT_FOUND = 404;
export const CREATED = 201;
export const UNAUTHORIZED = 401;
export const CREATE_SUCCESS = "Item created successfully"
export const CREATE_FAILURE = "Enter valid item details"
export const UPDATE_SUCCESS = "Item updated successfully"
export const UPDATE_FAIL = "Cannot update item"
export const GET_ITEM_SUCCESS = "Retrieved items successfully"
export const GET_ITEM_FAIL = "Cannot get items"
export const ITEM_NOT_FOUND = "Item not found!"
export const DELETE_SUCCESS = "Item deleted successfully"
export const DELETE_FAIL = "Cannot delete item"